FROM buildpack-deps:stretch

RUN set -ex; \
    apt-get update -y; \
    apt-get install -y --no-install-recommends \
        build-essential \
        lsb-release \
        python2.7 \
        python-pip \
        python3.5 \
        python3-pip \
        ruby \
        ruby-dev \
        rubygems \
    ; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*; \
    :

ADD https://github.com/krallin/tini/releases/download/v0.18.0/tini /usr/local/sbin/tini

RUN set -ex; \
    chmod +x /usr/local/sbin/tini; \
    pip2 --no-cache-dir install --upgrade pip; \
    hash -r pip2; \
    pip2 --no-cache-dir install --upgrade setuptools; \
    pip3 --no-cache-dir install --upgrade pip; \
    hash -r pip3; \
    pip3 --no-cache-dir install --upgrade pep440deb setuptools; \
    gem install --no-ri --no-rdoc fpm; \
    gem cleanup; \
    :

ENTRYPOINT ["/usr/local/sbin/tini", "-gw", "--"]
