FROM centos:7

ADD https://github.com/vishnubob/wait-for-it/raw/master/wait-for-it.sh /usr/local/bin/
ADD https://github.com/krallin/tini/releases/download/v0.18.0/tini /usr/local/sbin/tini
RUN set -ex; \
    chmod +x /usr/local/bin/wait-for-it.sh; \
    chmod +x /usr/local/sbin/tini; \
    sed -i s/^keepcache=.*/keepcache=1/ /etc/yum.conf; \
    yum -q -y install \
        epel-release \
        https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm \
    ; \
    yum -q -y install \
        postgresql11-server postgresql11-contrib \
        postgresql10-server postgresql10-contrib \
        postgresql96-server postgresql96-contrib \
        postgresql95-server postgresql95-contrib \
        postgresql94-server postgresql94-contrib \
    ; \
    yum clean all ; \
    :

RUN set -ex; \
    yum -q -y install \
        git \
        less \
        make \
        net-tools \
        openssl \
        procps-ng \
        psmisc \
        python2-pip \
        python-setuptools \
        rpm-build \
        rsync \
        sudo \
        yum-utils \
    ; \
    yum clean all ; \
    yum makecache fast; \
    :

RUN set -ex; \
    pip install "pytest"; \
    rm -rf ~/.cache/; \
    useradd --system testuser; \
    :

ENTRYPOINT ["/usr/local/sbin/tini", "-gw", "--"]
