FROM buildpack-deps:jessie

RUN set -ex; \
    apt-get update -y; \
    apt-get install -y --no-install-recommends \
        build-essential \
        lsb-release \
        python2.7 \
        python-pip \
        ruby \
        ruby-dev \
        rubygems \
        bats \
    ; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*; \
    :

ADD https://github.com/krallin/tini/releases/download/v0.18.0/tini /usr/local/sbin/tini

RUN set -ex; \
    chmod +x /usr/local/sbin/tini; \
    pip install pip==9.0.1; hash -r pip; \
    pip2 --no-cache-dir install --upgrade pip setuptools; hash -r pip2; \
    pip2 --no-cache-dir install --upgrade \
        pep440deb \
        "virtualenv<20" \
        virtualenv-tools\
    ; \
    gem install --no-ri --no-rdoc fpm; \
    gem cleanup; \
    :

ENTRYPOINT ["/usr/local/sbin/tini", "-gw", "--"]
